#Desactivo los detalles de la request
enableLoggingRequestDetails: false
server:
  error:
     #Al haber un error envia siempre message y los parametros
     include-message: always
     include-binding-errors: always
#Se asigna los niveles de Logging para mensajes en consola
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  #Cambio el formato de la hora en consola
  pattern:
    dateformat: HH:mm:ss
spring:
  main:
    #Desactivo el Banner de Spring Booy de consola
    banner-mode: off
  #Configuracion de conexion con MySQL
  datasource:
    # conexion con localhost
     url: jdbc:mysql://localhost:3306/gym?useSSL=true&useTimezone=true&serverTimezone=UTC
     username: root
     password: admin
    # conexion con base de datos
    #password: p7Mw1nO979WOfvW9AXdS
     #username: uyqaqtoeqwns6g02
     #url: jdbc:mysql://uyqaqtoeqwns6g02:p7Mw1nO979WOfvW9AXdS@bhzguzwfregpqsalpyry-mysql.services.clever-cloud.com:3306/bhzguzwfregpqsalpyry
     driver-class-name: com.mysql.cj.jdbc.Driver
  #Configuracion de JPA
  jpa:
    #Activa el mostrar el SQL ejecutado
    #show-sql: false
    #Revoco el manejo de la Transaccion a JPA (Recomendable)
    open-in-view: false
    properties:
      hibernate:
        #Dialecto que usa Hibernate para las querys
        dialect: org.hibernate.dialect.MySQL8Dialect
        #Muestra el SQL ejecutado en consola en Columna
        format_sql: false
  mail:
    username: gymprimefitnes@gmail.com
  security:
    oauth2:
      client:
        google:
          clientId: 320929967348-eor0sq7ja2gkem00m6i09rue80ar49s2.apps.googleusercontent.com
          clientSecret: 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
    jwt:
      secret: yGhqRjT4eibeqKq25Ps5DM2pWUdkVhPS

